import type {Metadata} from "next";
import "../globals.css";
import Link from "next/link";
import {getPages} from "@/sanity/sanity-utils";
import {Page} from "@/types/Page";

export const metadata: Metadata = {
    title: "loïc D. - Portfolio",
    description: "Generated by create next app",
};

// @ts-ignore
export default async function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {

    const pages = await getPages();

    return (
        <html lang="en">
        <body className="max-w-3xl mx-auto py-10">
        <header className="flex items-center justify-between">
            <Link href="/"
                  className="bg-gradient-to-r from-orange-400 wia-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold">Loïc
                D.</Link>
            <div className="flex items-center gap-5 text-small text-gray-600">
                {pages.map((page: Page) => {
                    return <Link key={page._id} href={`/${page.slug}`} className="hover:underline">
                        {page.title}
                    </Link>
                })}
            </div>
        </header>
        <main className="py-20">
            {children}
        </main>
        </body>
        </html>
    );
}
